apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2021-08-03T08:27:36Z"
  generation: 4
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-7.2.4
    component: queue-worker
    heritage: Helm
    release: openfaas
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:prometheus.io.scrape: {}
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"queue-worker"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"ack_wait"}:
                    .: {}
                    f:name: {}
                  k:{"name":"basic_auth"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"faas_function_suffix"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"faas_gateway_address"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"faas_nats_address"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"faas_nats_channel"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"faas_nats_queue_group"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"gateway_invoke"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"max_inflight"}:
                    .: {}
                    f:name: {}
                  k:{"name":"secret_mount_path"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/var/secrets"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"auth"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
    manager: Go-http-client
    operation: Update
    time: "2021-08-03T08:27:36Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"queue-worker"}:
                f:env:
                  k:{"name":"ack_wait"}:
                    f:value: {}
                  k:{"name":"max_inflight"}:
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-08-03T08:45:33Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: k3s
    operation: Update
    time: "2021-08-04T01:26:11Z"
  name: queue-worker-crop-monitor
  namespace: openfaas
  resourceVersion: "1690848"
  uid: c16a3ca5-9b80-4fae-815e-ee9604e6c451
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: queue-worker-crop-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      creationTimestamp: null
      labels:
        app: queue-worker-crop-monitor
    spec:
      containers:
      - env:
        - name: faas_nats_address
          value: nats.openfaas.svc.cluster.local
        - name: faas_nats_channel
          value: queue-worker-crop-monitor
        - name: faas_nats_queue_group
          value: faas
        - name: faas_gateway_address
          value: gateway.openfaas.svc.cluster.local
        - name: gateway_invoke
          value: "true"
        - name: faas_function_suffix
          value: .openfaas-fn.svc.cluster.local
        - name: max_inflight
          value: "10"
        - name: ack_wait
          value: 30s
        - name: secret_mount_path
          value: /var/secrets
        - name: basic_auth
          value: "true"
        image: openfaas/queue-worker:0.11.2
        imagePullPolicy: Always
        name: queue-worker-crop-monitor
        resources:
          requests:
            cpu: 50m
            memory: 120Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/secrets
          name: auth
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: auth
        secret:
          defaultMode: 420
          secretName: basic-auth
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-03T08:28:21Z"
    lastUpdateTime: "2021-08-03T08:28:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-03T08:27:36Z"
    lastUpdateTime: "2021-08-04T01:26:12Z"
    message: ReplicaSet "queue-worker-6c844b846f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
